---
title: "Summarize LiPD"
author: "David Edge"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Summarize LiPD}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

#Load LiPD files from lipdverse.org
D <- readLipd("http://lipdverse.org/testData/testData.zip")

#See a detailed summary of the first LiPD
L1 <- D[[1]]
lipdSummary(L1)

#Get a summary of all LiPDs in the directory, details of first 20
#Return time values in "AD" units if available
lipdDirSummary(D, printLen=20, timeUnits="AD", retTable = FALSE)

#save the summary table, sort to find age ensembles
dirSummary <- lipdDirSummary(D, printLen=20, timeUnits="AD", retTable = TRUE)
dirSummary[order(dirSummary$NumEns, decreasing=TRUE),]

#Format data as a tibble LiPD TS
TS1 <- extractTs(D)
tibTS <- ts2tibble(TS1)

#View dimensions of tibble object
dim(tibTS)

#Print summary of LiPD TS, first 50 lines only
lipdTSSummary(tibTS, printLen = 50)

#Print summary of a specific dataset
tibTS1 <- tibTS[tibTS$dataSetName == "165_1002C.Herbert.2000",]
lipdTSSummary(tibTS1)

#Find tree-ring data
tibTS2 <- tibTS[grep("tree", tibTS$archiveType),]
lipdTSSummary(tibTS2, printLen = 50)

#Filter for d18O data with time values in year AD
tibTS3 <- tibTS[grep("18o", tolower(tibTS$paleoData_variableName)),]
tibTS3 <- tibTS3[!is.blank(unlist(tibTS3$year)),]
tibTS3 <- tibTS3[unlist(lapply(tibTS3$year, function(x) !is.blank(unlist(x)))),]
lipdTSSummary(tibTS3, printLen = 50)
