#convert a neotoma2 site object to a LiPD object

neotoma2lipd <- function(site){
  if(class(site) != "site"){
    stop("You must enter a single 'site' (note multiple 'sites') object generated by the 'neotoma2' package")
  }
  
  
  
}


getGeoNeotoma2 <- function(site){
  
  if(class(site) != "site"){
    stop("You must enter a single 'site' (note multiple 'sites') object generated by the 'neotoma2' package")
  }
  
  #initialize geo object
  geo <- list()
  
  #get geo metadata
  sitemeta <- neotoma2::as.data.frame(site)
  
  geo$latitude <- mean(sitemeta$lat,na.rm = TRUE)
  geo$longitude <-  mean(sitemeta$long,na.rm = TRUE)
  geo$siteName <- sitemeta$sitename
  geo$description <- sitemeta$description
  geo$neotomaSiteId <- as.character(sitemeta$siteid)
  
  if(!is.na(sitemeta$area)){
    geo$lakeArea <- sitemeta$area
  }
  
  if(!is.na(sitemeta$elev)){
    geo$elevation <- sitemeta$elev
  }
  
  if(!is.na(sitemeta$notes)){
    geo$notes <- sitemeta$notes
  }
  
  return(geo)
}

getPubNeotoma2 <- function(site){
  
  if(class(site) != "site"){
    stop("You must enter a single 'site' (note multiple 'sites') object generated by the 'neotoma2' package")
  }
  
  pubMeta <- neotoma2::get_publications(site@siteid)
  
  nPubs <- length(pubMeta)
  
  if(nPubs == 0){
    return(NA)
  }
  
  #initialize pub object
  pub <- vector(mode = "list",length = nPubs)
  
  #lipd names converter (move this into data)
  nc <- googlesheets4::read_sheet("1Z44xjSxEDlWnThvYLsHFS9aFAN0FnYh2EdroMs9qe_Q")
  
  #plug it in
  for(p in 1:length(pub)){
    thisDf <- neotoma2::as.data.frame(pubMeta@publications[[p]])
    ndf <- names(thisDf)
    for(n in ndf){
      neo <- as.character(thisDf[n])
      lipdname <- as.character(nc[nc$neotomaname == n,2])
      if(!is.na(neo) & neo != "NA"){
        pub[[p]][[lipdname]] <- neo
      }
    }
    
  }
  
  return(pub)
}

getChronDataNeotoma2 <- function(site){
  
  if(class(site) != "site"){
    stop("You must enter a single 'site' (note multiple 'sites') object generated by the 'neotoma2' package")
  }
  
  #get conversion table (change this)
  cconv <- googlesheets4::read_sheet(ss = "1Z44xjSxEDlWnThvYLsHFS9aFAN0FnYh2EdroMs9qe_Q",sheet = "chronColumns")
  
  
  
  nChronData <- length(site@collunits)
  
  chronData <- vector(mode = "list",length(nChronData))
  for(cd in seq_len(nChronData)){
    #get all chroncontrols for this collunit
    tcu <- site@collunits[[cd]]@chronologies@chronologies
    nchronologies <- length(tcu)
    mt <- vector(mode = "list",length(nchronologies))
    for(cc in seq_len(nchronologies)){
      
      ac4lipd <- tcu[[cc]]@chroncontrols %>% 
        dplyr::arrange(depth)
      
      #calculate new columns
      
      ac4lipd$uncertainty <- rowMeans(abs(ac4lipd$chroncontrolage - cbind(ac4lipd$agelimityounger,ac4lipd$agelimitolder)),na.rm = TRUE)
      
      ac4lipd$depth_top <- ac4lipd$depth - ac4lipd$thickness/2
      ac4lipd$depth_bottom <- ac4lipd$depth + ac4lipd$thickness/2
      
      #rename
      ac4lipd <- ac4lipd %>% 
        dplyr::rename(ageYoung = agelimityounger, 
                      ageOld = agelimitolder, 
                      age = chroncontrolage,
                      age_type = chroncontroltype,
                      ageUnc = uncertainty,
                      neotomaChronConrolId = chroncontrolid)
      
      i14c <- which(grepl(pattern = "carbon",ac4lipd$age_type,ignore.case = TRUE))
      
      #separate into age and age14C
      if(length(i14c) > 0){
        ac4lipd$age14C <- NA
        ac4lipd$age14C[i14c] <- ac4lipd$age[i14c]
        ac4lipd$age[i14c] <- NA
        #and uncertainty
        ac4lipd$age14CUnc <- NA
        ac4lipd$age14CUnc[i14c] <- ac4lipd$ageUnc[i14c]
        ac4lipd$ageUnc[i14c] <- NA
      }
      
      ac4lipd <- ac4lipd %>% 
        dplyr::select(depth,starts_with("depth"),thickness,age,starts_with("age"),everything())
      
      
      
      #create chronData measurement table
      acn <- names(ac4lipd)
      mt[[cc]] <- list()
      
      for(cn in seq_along(acn)){#iterate through columns
        mt[[cc]][[acn[cn]]] <- list()
        mt[[cc]][[acn[cn]]]$number <- cn
        mt[[cc]][[acn[cn]]]$variableName <- acn[cn]
        mt[[cc]][[acn[cn]]]$values <- as.vector(as.matrix(ac4lipd[cn]))
        
        
        wr <- which(acn[cn] == cconv$variableName)
        if(length(wr) == 1){
          mt[[cc]][[acn[cn]]]$units <- cconv$units[wr]
        }else{
          mt[[cc]][[acn[cn]]]$units <- "unknown"
        }
        if(length(wr) == 1){
          mt[[cc]][[acn[cn]]]$description <- cconv$description[wr]
        }
        mt[[cc]][[acn[cn]]]$TSid <- paste0("neotomaChronologyID_",site@collunits@collunits[[cd]]@chronologies@chronologies[[cc]]@chronologyid,acn[cn])
        
      }
      
    }
    chronData[[cd]]$measurementTable <- mt
    
  }
  
  return(chronData)
  
  
}

#TBD
#getPaleoDataNeotoma2 <- function()

#build into lipd file

neotoma2lipd <- function(site){
  #initialize LiPD
  
  L <- list()
  
  L$geo <- getGeoNeotoma2(site)
  L$pub <- getPubNeotoma2(site)
  #L$paleoData <- getPaleoDataNeotoma2(site)
  L$chronData <- getChronDataNeotoma2(site)
  
  sn <- L$geo$siteName
  fa <- strsplit(L$pub[[1]]$author,",")[[1]][1]
  py <- L$pub[[1]]$year
  
  L$dataSetName <- paste(sn,fa,py,sep = ".") %>% 
    str_remove_all("[^a-zA-Z0-9.]")
  
  L$datasetId <- paste0("neotomaSiteId_",site@siteid)
  timestamp <- lubridate::now(tzone = "UTC")
  version = "1.0.0"
  thisChange <- list(version = "1.0.0",
                     curator = "lipd2neotoma",
                     timestamp = paste(timestamp,lubridate::tz(timestamp)),
                     notes  =  "Starting the changelog")
  
  L$changelog <- list(thisChange)
  
  L$lipdVersion <- 1.3
  
  dataContributor <- neotoma2::get_contacts(familyname = fa)
  L$dataContributor <- try(dataContributor@contacts[[1]]$contactid,silent = TRUE)
  L$originalDataUrl <- paste0("https://data.neotomadb.org/datasets/",site@siteid)

  #make this work with multiple collection units and datasets  
  L$dataDoi <- site@collunits@collunits[[1]]@datasets@datasets[[1]]@doi %>% 
    unlist() %>% 
    paste(collapse = "; ")
  
  L$createdBy <- "neotoma2lipd"
  
  #take a guess at archive type
  if(grepl(L$geo$siteName,pattern = "lake",ignore.case = T)){
    L$archiveType <- "LakeSediment"
  }else if(grepl(L$geo$siteName,pattern = "bog",ignore.case = T) |
           grepl(L$geo$siteName,pattern = "fen",ignore.case = T) |
           grepl(L$geo$siteName,pattern = "peat",ignore.case = T)){
    L$archiveType <- "Peat"
  }else{
    L$archiveType <- "unknown"
  }
  
  
  
  
    return(L)
  
  
  
  
}
